version: '3'

services:
  budget:
    build: .
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./.env:/app/.env
    command: ai-config --status
    environment:
      - PYTHONUNBUFFERED=1